# Generated by Django 4.1.3 on 2022-11-12 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=15)),
                ('ph_no', models.IntegerField(default=False)),
                ('cust_id', models.IntegerField(default=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(max_length=10)),
                ('pro_id', models.IntegerField(default=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('S', 'Sale'), ('SR', 'Service')], max_length=5)),
                ('customer', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Customer_app.customer')),
                ('product', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Customer_app.product')),
            ],
        ),
    ]
